name: 'Delete packages'
description: 'Delete removed packages from the package server'
inputs:
  universe:
    description: 'Name of the universe'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/delete-packages'
  args:
    - ${{ inputs.universe }}
